<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Crystal Words Bank
 *
 * # The Words Bank of Crystal Platform. **Crystal Bank**  have a huge collection and **Words Bank** is one of them. Words bank have so many words and more information about that word. Each words have one or more meaning from another language with a description. For now all words catogarzied as follow. <table>   <tr>     <th>ID</th>     <th>CATOGARY</th>   </tr>   <tr>     <td>1</td>     <td>ICT</td>   </tr> <table>  As the Bank is built with a NoSQL database, all information about a single Data is with that word, and all words may not have same information. And so many information is yet to come. Current data will retrive, <ul>   <li>Word in English</li>   <li>Word in Sinhala</li>   <li>Meaning in Sinhala</li>   <li>Descrtipion in Sinhala</li>   <li>Description in English</li>   <li>ID</li>   </ul>
 *
 * OpenAPI spec version: v0.0.0.1
 * Contact: contact@dev.pmkg.lk
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.7
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for wordsGet
     *
     * Get All Words available from Crystal Words Bank.
     *
     */
    public function testWordsGet()
    {
    }

    /**
     * Test case for wordsOptions
     *
     * .
     *
     */
    public function testWordsOptions()
    {
    }

    /**
     * Test case for wordsPost
     *
     * POST Request will update any data in the Bank.
     *
     */
    public function testWordsPost()
    {
    }
}
